#Task level Varaiables
- name: Varaiables from play level
  hosts: localhost
  Vars: 
    Name: "Siva prasad"
    Course: "DevOps"
    Trainer: "Siva sir"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hello My name is siva, iam learning DevOps, and iam learning from siva sir"