#Task level Varaiables
- name: Varaiables from play level
  hosts: localhost
  Vars: 
    Name: "Siva prasad"
    Course: "DevOps"
    Trainer: "Siva sir"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hello My name is {{Nmae}}, iam learning {{Course}}, and iam learning from {{Trainer}}"